### ISSUE TITLE
not able start the application 

### ISSUE THREAD

**Issue by pshewale-dev** [TomHumphries/simple-nvr#4]
getting the below are while running the application .
| Require stack:
0|nvr      | - /home/pshewale/simple-nvr/nvr.js
0|nvr      |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
0|nvr      |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
0|nvr      |     at require (internal/modules/cjs/helpers.js:74:18)
0|nvr      |     at Object.<anonymous> (/home/pshewale/simple-nvr/nvr.js:1:17)
0|nvr      |     at Module._compile (internal/modules/cjs/loader.js:999:30)
0|nvr      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
0|nvr      |     at Module.load (internal/modules/cjs/loader.js:863:32)
0|nvr      |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
0|nvr      |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|nvr      |     at Module._compile (internal/modules/cjs/loader.js:999:30) {
0|nvr      |   code: 'MODULE_NOT_FOUND',
0|nvr      |   requireStack: [ '/home/pshewale/simple-nvr/nvr.js' 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/79329378/189921244-34afab98-a614-42cf-a082-ceb98fe47995.png">

**Comment by pshewale-dev** [comment]
issue fix after running this  npm i require-hook command
