### ISSUE TITLE
Error when trying to start app

### ISSUE THREAD

**Issue by b3nis** [TomHumphries/simple-nvr#6]
Getting following error - dunno if it's NPM/PM2 or simple-nvr?
```

0|nvr      | Require stack:
0|nvr      | - /home/benjamin/simple-nvr-master/nvr.js
0|nvr      |     at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
0|nvr      |     at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
0|nvr      |     at require (node:internal/modules/helpers:121:18)
0|nvr      |     at Object.<anonymous> (/home/benjamin/simple-nvr-master/nvr.js:1:17)
0|nvr      |     at Module._compile (node:internal/modules/cjs/loader:1255:14)
0|nvr      |     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
0|nvr      |     at Module.load (node:internal/modules/cjs/loader:1113:32)
0|nvr      |     at Module._load (node:internal/modules/cjs/loader:960:12)
0|nvr      |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|nvr      |     at Module._compile (node:internal/modules/cjs/loader:1255:14) {
0|nvr      |   code: 'MODULE_NOT_FOUND',
0|nvr      |   requireStack: [ '/home/benjamin/simple-nvr-master/nvr.js' ]
0|nvr      | }
```

**Comment by ghost** [comment]
I had the same issue. I followed the fix provided in [Issue #4](https://github.com/TomHumphries/simple-nvr/issues/4) and ran `npm i require-hook`. This fixed it for me.
